### valid request
curl -X POST https://5df2woqeqc.execute-api.us-east-1.amazonaws.com/dev/ \
  --data '{ "inputWords": ["table", "sleep"] }'

### invalid request
curl -X POST https://5df2woqeqc.execute-api.us-east-1.amazonaws.com/dev/ \
  --data '{ "inputWords": ["table", "sleep", "invalid"] }'
